objectstore.crypto.name=OfflinePacketCryptoServiceImpl
keymanager.persistence.jdbc.driver=org.postgresql.Driver
keymanager_database_url=jdbc:postgresql://10.0.9.133:31432/mosip_keymgr
keymanager_database_username=postgres
keymanager_database_password=mosipuser1234
