objectstore.crypto.name=OfflinePacketCryptoServiceImpl
keymanager.persistence.jdbc.driver=org.postgresql.Driver
keymanager_database_url=jdbc:postgresql://10.0.9.133:31432/mosip_keymgr
keymanager_database_username=postgres
keymanager_database_password=mosipuser1234
mosip.kernel.keymanager.hsm.keystore-type=PKCS11
mosip.kernel.keymanager.hsm.config-path=/home/mosip/softhsm-application.conf
mosip.kernel.keymanager.hsm.keystore-pass=1234
mosip.security.provider.name=SunPKCS11-pkcs11-proxy
mosip.kernel.keymanager.keystore.keyreference.enable.cache=true
