objectstore.crypto.name=OfflinePacketCryptoServiceImpl
keymanager.persistence.jdbc.driver=org.postgresql.Driver
keymanager_database_url=jdbc:postgresql://10.0.9.133:31432/mosip_keymgr
keymanager_database_username=postgres
keymanager_database_password=mosipuser1234
mosip.kernel.keymanager.hsm.keystore-type=PKCS11
mosip.kernel.keymanager.hsm.config-path=/home/mosip/softhsm-application.conf
mosip.kernel.keymanager.hsm.keystore-pass=1234
mosip.security.provider.name=SunPKCS11-pkcs11-proxy
mosip.kernel.keymanager.keystore.keyreference.enable.cache=true
mosip.kernel.keymanager.certificate.default.common-name=www.mosip.io
mosip.kernel.keymanager.certificate.default.organizational-unit=MOSIP-TECH-CENTER
mosip.kernel.keymanager.certificate.default.organization=IITB
mosip.kernel.keymanager.certificate.default.location=BANGALORE
mosip.kernel.keymanager.certificate.default.state=KA
mosip.kernel.keymanager.certificate.default.country=IN
mosip.kernel.partner.sign.masterkey.application.id=PMS
mosip.kernel.partner.allowed.domains=AUTH,DEVICE,FTM
mosip.kernel.keymanager.autogen.appids.list=ROOT,KERNEL:SIGN,PRE_REGISTRATION,REGISTRATION,REGISTRATION_PROCESSOR,ID_REPO,KERNEL:IDENTITY_CACHE,RESIDENT,PMS
mosip.kernel.keymanager.autogen.basekeys.list=RESIDENT:mpartner-default-resident
mosip.kernel.certificate.sign.algorithm=SHA256withRSA
mosip.kernel.crypto.asymmetric-algorithm-name=RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING
mosip.kernel.crypto.symmetric-algorithm-name=AES/GCM/PKCS5Padding
mosip.kernel.data-key-splitter=#KEY_SPLITTER#
mosip.kernel.crypto.gcm-tag-length=128
mosip.kernel.crypto.sign-algorithm-name=RS256
mosip.kernel.zkcrypto.masterkey.application.id=KERNEL
mosip.kernel.zkcrypto.masterkey.reference.id=IDENTITY_CACHE
mosip.kernel.zkcrypto.publickey.application.id=IDA
mosip.kernel.zkcrypto.publickey.reference.id=PUBLIC_KEY
mosip.kernel.zkcrypto.wrap.algorithm-name=AES/ECB/NoPadding
mosip.kernel.zkcrypto.derive.encrypt.algorithm-name=AES/ECB/PKCS5Padding
mosip.kernel.keymanager.113nothumbprint.support=true
mosip.kernel.partner.issuer.certificate.allowed.grace.duration=30
