# ===============================
# AUDIT MANAGER DATABASE CONFIG
# ===============================

# Indispensable pour AUDITMANAGER
javax.persistence.jdbc.driver=org.postgresql.Driver
javax.persistence.jdbc.url=jdbc:postgresql://10.0.9.133:31432/mosip_audit
javax.persistence.jdbc.user=postgres
javax.persistence.jdbc.password=mosipuser1234

# AUDIT MANAGER
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://10.0.9.133:31432/mosip_audit
spring.datasource.username=postgres
spring.datasource.password=mosipuser1234


audit_database_url=jdbc:postgresql://10.0.9.133:31432/mosip_audit?currentSchema=audit
audit_database_username=postgres
audit_database_password=mosipuser1234

# ===============================
# HIBERNATE
# ===============================

#logging.level.org.springframework.jdbc.datasource=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.io.mosip.kernel.dataaccess=DEBUG
hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
hibernate.hbm2ddl.auto=none
hibernate.jdbc.lob.non_contextual_creation=true
hibernate.show_sql=false
hibernate.format_sql=false
hibernate.connection.charSet=utf8
hibernate.cache.use_second_level_cache=false
hibernate.cache.use_query_cache=false
hibernate.cache.use_structured_entries=false
hibernate.generate_statistics=false
hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
